// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("201349a7-45e0-463a-9604-55445842b02d"),
                            Email = "pop.ion@gmail.com",
                            Name = "Popa Ion",
                            Password = "pass1",
                            TypeId = new Guid("9443f48b-8a86-4818-b5e9-514d4cd0512b")
                        },
                        new
                        {
                            Id = new Guid("11c14a98-066a-4851-aff1-20e149d9fcd8"),
                            Email = "pop.ion2@gmail.com",
                            Name = "Popa Ion2",
                            Password = "pass1",
                            TypeId = new Guid("9443f48b-8a86-4818-b5e9-514d4cd0512b")
                        },
                        new
                        {
                            Id = new Guid("a5e573f1-4d6a-46a1-8fe6-419d49558816"),
                            Email = "sef.ion2@gmail.com",
                            Name = "Sef Ion",
                            Password = "pass1",
                            TypeId = new Guid("4e57b9ca-9a18-4255-8f17-7591f63d1917")
                        },
                        new
                        {
                            Id = new Guid("164305dc-2f2e-4309-9d65-e5a65261ec72"),
                            Email = "sef.ion2@gmail.com",
                            Name = "Sef Ion2",
                            Password = "pass1",
                            TypeId = new Guid("4e57b9ca-9a18-4255-8f17-7591f63d1917")
                        });
                });

            modelBuilder.Entity("DataLayer.Models.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9443f48b-8a86-4818-b5e9-514d4cd0512b"),
                            Name = "USER"
                        },
                        new
                        {
                            Id = new Guid("4e57b9ca-9a18-4255-8f17-7591f63d1917"),
                            Name = "ADMIN"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.HasOne("DataLayer.Models.UserType", "Type")
                        .WithMany("Users")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DataLayer.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
